//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aeroport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aeroport()
        {
            this.vols = new HashSet<vols>();
            this.vols1 = new HashSet<vols>();
        }
    
        [Key]
        public int Id_aero { get; set; }
        public string ville { get; set; }
        public Nullable<int> latitude { get; set; }
        public Nullable<int> latideg { get; set; }
        public string latidirection { get; set; }
        public Nullable<int> longtitude { get; set; }
        public Nullable<int> longdeg { get; set; }
        public string longdirection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vols> vols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vols> vols1 { get; set; }
    }
}
