//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flyapp_DBEntities : DbContext
    {
        public flyapp_DBEntities()
            : base("flyapp_DBEntities")
        {
        }
    
       /* protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }*/
    
        public virtual DbSet<aeroport> aeroport { get; set; }
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<vols> vols { get; set; }
    }
}
